var ollMap = {
  1: [
    "R' U' F R' F' R2 U R B' R' B",
    "L U F' L F L2 U' L' B L B'",
    "L U2 L2 B L B' U2 L' B L B'",
    "R' U2 R2 B' R' B U2 R B' R' B",
    "B U' B2 D' F R' F' D B2 U B'",
    "L' B2 R2 B R' B L U2 B' R' B",
    "F' U F2 D B' R B D' F2 U' F",
    "R B2 L2 B' L B' R' U2 B L B'",
    "L R' F R U2 F' U2 F' U2 F U2 L'",
    "L R' F' L' U2 F U2 F U2 F' U2 R",
    "L U F' L F L2 B' U' B L U' L'",
    "R' U' F R' F' R2 B U B' R' U R",
    "R' U' F R' F' R2 B U' L U L' B'",
    "L U F' L F L2 B' U R' U' R B",
    "L U F' L F L2 B2 R B R' U' B",
    "R' U' F R' F' R2 B2 L' B' L U B'",
    "R2 B2 L' B R' B2 L2 U L' U B' R'",
    "L2 B2 R B' L B2 R2 U' R U' B L",
    "L R' F R U2 B' R2 F' R2 B U2 L'",
    "L R' F' L' U2 B L2 F L2 B' U2 R",
  ],
  2: [
    "B L' B' L U L2 F' L' F U' L'",
    "F' L F L' U' L2 B L B' U L",
    "B' R' B U2 F' U2 F U2 B' R B",
    "F R F' U2 B U2 B' U2 F R' F'",
    "L U L' B' R' U' F R' F' R2 B",
    "L' U' L F R U B' R B R2 F'",
    "L B' R2 F' R F2 R' F R2 B L'",
    "L' F R2 B R' B2 R B' R2 F' L",
    "R U2 L' B L U2 L' B' L U2 R'",
    "L2 F2 R' F2 L' F R2 U2 R' F' L'",
    "L2 B2 R B2 L B' R2 U2 R B L",
    "R B R' U L U' L' R U B' U' R'",
    "R' F' R U' L' U L R' U' F U R",
    "L F L' U' B U L U2 F' U L' B'",
    "L' B' L U F' U' L' U2 B U' L F",
    "B U B' R' U R B2 L' B' L U' B'",
    "L F U2 R' F R F2 L' U B' U B",
    "B' U R B' R' B2 L2 F' L' F U' L'",
    "F U2 B' R B2 U2 B' R' B U2 B' F'",
    "F2 D B' R' B D' F' R U2 R' U' F'",
    "B2 D' F R F' D B R' U2 R U B",
    "B L B2 D2 F R D F2 D B U' R2",
    "F' L' F2 D2 B' R' D' B2 D' F' U R2",
    "B2 U L' D' R2 D' B' R' D2 L2 F' L'",
    "F2 U' L D R2 D F R D2 L2 B L",
  ],
  3: [
    "B' F R F' U2 F R B' R B2 F'",
    "L F2 L2 U2 L F L' U2 L2 F2 L'",
    "R' F2 R2 U2 R' F R U2 R2 F2 R",
    "B' U' R' U R B R B U B' U' R'",
    "L U2 L F' L' F U F U F' U L'",
    "F' L' U B' U B U' B' U2 B L F",
    "F U R U' R' F' R B U B' U' R'",
    "B L U L' U' B' R' U' F' U F R",
    "L F R U2 R' U F' L' U B' U B",
    "B' R B L' B R' B2 L U2 L' B L",
    "R B R' U2 R B2 L' B R' B L B'",
    "F R' F' R U F D B' R' B D' F'",
    "F U F' L' U L2 D R' F' R D' L'",
    "L F' L' F U2 L' B' R' U2 R B L",
    "R2 D L' B' L D' R' U' R' F' U F",
    "L U L' B' U' B' D' F R' F' D B2",
    "R' F' U F U' R2 D L' B' L D' R'",
    "R' U2 R B L F U2 F2 L F L2 B'",
    "R U2 R' F' U F2 D B' R B D' F'",
    "R' F2 L F L2 U2 L F R B U2 B'",
    "L' D' R B R' D L2 U L' B' U2 B",
    "B L U L' B' R2 D' L F' L' D R2",
    "F2 D B' R' B D' F2 L' B' U B L",
    "B F2 D2 B2 R' B2 D2 F L F L2 B'",
    "B' D2 F2 R' F2 D2 B2 F' L F L2 B'",
  ],
  4: [
    "L R' F' R U2 R' F' L F' L2 R",
    "F R2 F2 U2 F R' F' U2 F2 R2 F'",
    "B' R2 B2 U2 B' R' B U2 B2 R2 B",
    "L U F U' F' L' F' L' U' L U F",
    "B' U2 B' R B R' U' R' U' R U' B",
    "R B U' L U' L' U L U2 L' B' R'",
    "R' U' F' U F R F' L' U' L U F",
    "L' B' U' B U L F U R U' R' F'",
    "B' R' F' U2 F U' R B U' L U' L'",
    "L F' L' B L' F L2 B' U2 B L' B'",
    "F' L' F U2 F' L2 B L' F L' B' L",
    "F D B' R B D' F' U' R' F R F'",
    "R' F R F' U' R' D' L F L' D R",
    "B' R B R' U2 B L F U2 F' L' B'",
    "F2 D' B L B' D F U F R U' R'",
    "B' U' B L U L D R' F R D' L2",
    "R B U' B' U' R D L' B L D' R2",
    "F R U' R' U F2 D' B L B' D F",
    "F U2 F' L' B' R' U2 R2 B' R' B2 L",
    "F' U2 F R U' R2 D' L F' L' D R",
    "F R2 B' R' B2 U2 B' R' F' L' U2 L",
    "R2 D' L F L' D R2 B L U' L' B'",
    "L' R2 D2 L2 F L2 D2 R' B' R' B2 L",
    "F R2 B' R' B' D2 F2 L F2 D2 B2 F'",
    "L D2 R2 F R2 D2 L2 R B' R' B2 L",
  ],
  5: [
    "B' F R B' R2 B R B' R B2 F'",
    "B' R2 F R F' R U' R' U R B",
    "L' U B L' B' L B' U2 B U L",
    "R' F' L' U2 L F R' F R F' R",
    "L R2 D2 L D2 L' R F' L' F R",
    "F' L' U' L U L' U L F R U' R'",
    "F D' F L F L' F' D F' R' F' R",
    "R' F R' F2 U' F U R2 U' B U2 B'",
    "B' U2 B U' L2 U F' L F L' U' L2",
    "B2 U' B' R B R' U B2 U' L U2 L'",
    "L' U2 R B U B2 R B R' U' L R'",
    "R' U L U' R U2 L2 B L B2 U B",
    "L U' F U R B U' B' R' F' U2 L'",
    "B2 R' U F' U' F R B2 U' L U2 L'",
    "B2 F2 L' F L' B' U2 L' B L' B2 F",
    "R' U' R2 U2 B' D B U2 B2 D' B2 R'",
    "F2 D L D' F D L' D' F2 R' F' R",
    "R' D' F2 D F L' R2 U2 L R' U F",
    "F' L' D F2 U F2 D' L' B L2 B' F",
    "R' F' U B2 F' D2 F' D2 B2 F' U R",
    "F2 L2 R2 B2 R' B2 L' R2 F L' F R",
    "L' R' F2 L' B' R U2 R' B L2 F' R",
    "F' L2 B L2 F L2 B2 R B' R' B2 L2",
    "F D R' B2 R' D' R D B2 R D' F'",
    "F R' F R' D2 L2 B2 L2 D2 R F2 R",
  ],
  6: [
    "L R' F' L F2 L' F' L F' L2 R",
    "L F2 R' F' R F' U F U' F' L'",
    "B U' L' B L B' L U2 L' U' B'",
    "F' L F' L' F2 R U' B U' B' R'",
    "R B R' U2 L U' L' U2 R B' R'",
    "F R B U2 B' R' F R' F' R F'",
    "F U F R' D R' D' R2 F' U' F'",
    "B' R B R' U' B L U2 L' U' B'",
    "F R' D' R' D2 L B2 L' D' R2 F'",
    "B U B' U' B' U' R U B2 U' B' R'",
    "B' F U' B U R U' B' U B R' F'",
    "R B U' B2 U' B2 U B L' B2 L R'",
    "L' B L F L' B' U R U' L R' F'",
    "R' U' R B R B2 L' B2 L R' U B'",
    "L2 U L F' L' F U' L2 U B' U2 B",
    "L2 F L U R U' L' F' L2 F R' F'",
    "F R2 F' R2 B R2 B' R' B R' U2 B'",
    "B2 U' B L U' L' B' U B2 L U2 L'",
    "B' F D' R' D B2 F' L U2 L' U' B'",
    "F' U B2 L U B' L' B U' L' B2 F",
    "L' F2 L2 R2 B2 F' R F' L2 R B2 L",
    "R' F R' B R2 F2 U2 F2 R2 B' R2 F'",
    "R' D' F L2 F D F' D' L2 F' D R",
    "R2 B F' U2 L2 B D2 B' L' F L' B'",
    "B' F' D2 L' B U2 B' L D2 B U2 F",
  ],
  7: [
    "F' U2 F U F' U L' U' L U F",
    "L R' F L F L' F L F2 L2 R",
    "B L' B' U B L B' U2 F U F'",
    "B F' L2 F L2 B' L2 B L B' L",
    "B F' U' F2 R' F' R2 U' R' U2 B'",
    "B L F U' R' F R F2 U L' B'",
    "L' U' F R2 D B' D' R2 F' U2 L",
    "B U' R' U' R2 B' R' B2 U' B' U' B'",
    "R B' R B R' B L U L' U B' R'",
    "L' B' U' B U2 B L' B' L2 F U' F'",
    "R' F R' F' R2 U2 B' F R B R' F'",
    "B2 U B L' B L2 U L' U2 R B2 R'",
    "R' D2 L U' F U F' U L' D2 U' R",
    "B U2 B' R' U F2 L F L' U' F R",
    "B D L B2 U F U' B2 F' L' D' B'",
    "F U L2 R' D2 R' D2 L2 R' U R' F'",
    "L' D F' D' L2 B L2 D F D' B' L",
    "B L2 D' B R' U' R U B' D L2 B'",
    "L' B R2 B2 U2 B U2 L2 B R2 B' L'",
    "L' B L2 F2 R' D R F2 L2 B' U L",
    "F R2 F' D2 B' F L2 D2 B R F' R",
    "F D2 U' B2 U L U2 B2 D2 R U' F",
    "F' U2 B' D2 L' B U2 B' L D2 B F",
    "L' B' U2 B2 R2 F' L2 D2 F R2 B' L'",
    "F' D2 B2 L2 F2 U2 B D2 B R F' R",
  ],
  8: [
    "F U2 F' U L' U' L U' F U' F'",
    "R' U R U B U2 B' U2 R' U2 R",
    "B' F R' B' R' B R' B' R2 B2 F'",
    "L' R B2 R' B2 L B2 L' B' L B'",
    "L' U' L' B2 D' B' D B' L U L",
    "F' L F' L' F L' B' U' B U' L F",
    "B' R B R2 F R U R' U' R' F' R2",
    "R' B' F R' F' R2 F R2 F' R' B R",
    "B L U L' U2 L' B L B2 R' U R",
    "F' L' U' L U2 B L U L' U' B' F",
    "R U R B' R D' R' D R' B U' R'",
    "R B U' L B' U' B U B L' B2 R'",
    "L U L' B2 U' R' U R2 B R' U' B",
    "R' F' L2 R U' L U' R' F2 L F' R",
    "L2 F' L' F L' B' R' U2 R2 B' R' B2",
    "B' R B L B2 L2 B2 R' B2 L2 B2 L'",
    "F L2 F' L' U2 L F2 R' F' L2 R F'",
    "R2 F2 L F2 R F' L2 U' L U' F R",
    "B2 R B R' U' B' F2 D2 B' D2 B' F2",
    "L R' F2 R F D' L2 U' L2 D F L'",
    "B U L' U' L2 D' B2 U2 B2 D L' B'",
    "R' U' B2 F D2 F D2 B2 F U' F R",
    "L' B' R B' L2 R F2 L B2 L2 R2 F2",
    "R' D2 U L2 U' B' U2 L2 D2 F' U R'",
    "R D2 L2 B2 R2 U2 L' D2 L' F' R F'",
  ],
  9: [
    "L' U' B' U B U' L U' L' U2 L",
    "L U L' U' L' B L2 U L' U' B'",
    "B U2 B2 F R' B R' B' R B F'",
    "B L2 F' L D' L' D L' F L' B'",
    "L' U R B L' B' D' B' D L2 R'",
    "L F' L2 B L' D2 B D2 B2 L2 F",
    "L F' U' F2 U' F2 U F L' F' U F",
    "B' R B2 L' B R' B2 L U' L U' L'",
    "R' F' L U L' U' F L' R B L B'",
    "L' B L U' B D' U B U' B' D B'",
    "L F U2 R' F R F2 L F' L' F L'",
    "B L U' L' B F' L' B' L F U B'",
    "L' U' L B U2 F U F' L' U2 L B'",
    "F' L' U' L2 U2 B L B' U2 L' U' F",
    "R B2 U B' U B R B' R' U2 B2 R'",
    "L' U2 F R F' L B F U2 B' R' F'",
    "F' L D' L' D' B2 D B' L B' D F",
    "B' R' U R2 B2 L' B2 R' B L2 U' L'",
    "R F R' U R F' L2 D' B' D L2 R'",
    "B D' L B2 L F' L' B2 F L' D B'",
    "L B R2 B' L2 U2 B' U2 B2 R2 B' L",
    "L F2 R2 F2 L2 B R2 B R2 B' L R2",
    "L' B' D L2 F U' F' U' L2 D' B2 L",
    "F2 L2 B' R2 B2 F L' F L' B R2 B2",
    "B L D' B2 U' R' U2 R B2 D L2 B'",
  ],
  10: [
    "B U L U' L' U B' U B U2 B'",
    "B' U' B U B L' B2 U' B U L",
    "L' U2 L2 R' F L' F L F' L' R",
    "L' B2 R B' D B D' B R' B L",
    "L2 R D' B D B L B' R' U' L",
    "B' R B2 L' B D2 R D2 R2 B2 L",
    "B' R U R2 U R2 U' R' B R U' R'",
    "L' U' L' B L B' L2 F' L' F2 U' F'",
    "B2 R B U B U' B' R' B2 L' B' L",
    "L F' L2 B L' F L2 B' U B' U B",
    "B2 U2 B' L B L' U' L U' B' L' B'",
    "R B L' B L B' R' F R B' R' F'",
    "B U B' L' U2 R' U' R B U2 B' L",
    "R' U2 L F2 U F2 U' F' R' F' L' R2",
    "F' L2 U' L U' L' F' L F U2 L2 F",
    "B2 R B R2 U2 R B L F' L F L2",
    "F' R' F U' F' R B2 D L D' B2 F",
    "B U' F2 U R' D' L2 D' L' D2 R B'",
    "R' U' F U' R' F' L D F2 D' L' R2",
    "L' B2 D' B2 U2 B D B' U2 L2 U' L'",
    "B' L' F2 L B2 U2 L U2 L2 F2 L B'",
    "B' R2 F2 R2 B2 L' F2 L' F2 L B' F2",
    "R2 B2 L F2 L2 R' B R' B L' F2 L2",
    "L' B' D L2 U F U2 F' L2 D' B2 L",
    "F' L' U2 F R' F D2 R' B2 D2 R2 F'",
  ],
  11: [
    "B' F2 R F' R F R2 F' R B F'",
    "F R U R' U' R B' R B R2 F'",
    "L' B' U' B2 L' B' L2 U' L' U2 L",
    "L' U2 F' U' F2 R' F' R2 U' L R'",
    "L' U2 L U F R B U B' R' F'",
    "R' F2 L' R2 B L' B' L2 R2 F2 R",
    "L' B' R2 D' R' D2 B' D' B2 L R'",
    "F2 D B' R' B D' F' R U R' F'",
    "L2 B2 R B2 L B L' B R' B2 L2",
    "B U2 R' F2 D' L' D F2 R U' B'",
    "F R2 B2 D2 B D2 R F' R2 B R'",
    "L' R U B U' B U B2 U' B2 L R'",
    "B L U' L2 U2 L2 U L2 U L U' B'",
    "B' U2 B U' L2 U F U' F2 L' F L'",
    "F2 U R' F' R F' R' F' R F2 U' F2",
    "L2 U' L2 B L' B' L' B L' B' U L2",
    "R B' R' B' R2 B2 U2 B U2 B R2 B2",
    "F' L' B U L U' L' B' U2 L U F",
    "R U2 F R2 U' R2 U R2 U F' U R'",
    "B' R' U2 F R B' R2 F' R' B R' B",
    "B2 L2 B R B' L2 R' B2 U' L U' L'",
    "R2 F2 R F2 L' R2 B L' B R' B2 L2",
    "F D' R B' F2 R B R' F2 R' D F'",
    "F2 L2 R2 B' R' B L2 R' F2 L' U2 L",
    "L2 F' L2 F R' F' D2 R2 B' R2 D2 R",
  ],
  12: [
    "L R2 F' R F' R' F2 R F' L' R",
    "R' F' U' F U F' L F' L' F2 R",
    "B L U L2 B L B2 U B U2 B'",
    "B U2 R U R2 F R F2 U B' F",
    "F R2 B F2 L' B L B2 F2 R2 F'",
    "B L F2 D F D2 L D L2 B' F",
    "R B U' B' R2 D' L F L' D R",
    "R2 D' L F L' D R F' U' F R",
    "L' U2 F R2 D B D' R2 F' U L",
    "L F2 R2 D2 R D2 F' R F2 L' F",
    "B F' U' L' U L' U' L2 U L2 B' F",
    "L' B' U B2 U2 B2 U' B2 U' B' U L",
    "L U2 L' U B2 U' R' U R2 B R' B",
    "B2 U B2 L' B L B L' B L U' B2",
    "R B L' U' B' U B L U2 B' U' R'",
    "F2 L B L' B' F L' F U2 B' U2 B",
    "R' F R B R' F2 L F' L' F2 R B'",
    "R' F2 U F U' L U F' U' L' F2 R",
    "B U2 L R B U B' U' L' R' U2 B'",
    "L F U2 R' F' L F2 R F L' F L'",
    "F D' R F U2 F' R' F U2 F' D F'",
    "R2 B2 R' U2 R' U2 R B2 R2 F R F'",
    "L2 B2 L' F' L B2 F L2 U B' U B",
    "R2 B2 F2 L F L' B2 F R2 B U2 B'",
    "F' U2 R' F2 D R2 U' R2 D' R U' F",
  ],
  13: [
    "L U F U' F2 L' F U F U' F'",
    "B U' F' U B' U' L' U' L U F",
    "F' L' B L F L' B2 U' B U L",
    "B U B' L R2 F R F' L' U' R",
    "B2 R B R2 U2 R U' B L U L'",
    "R B U B2 D' B U' B' D B R'",
    "F' U2 F U F' U F2 U R U' R' F'",
    "B U R' U R U B U2 B' R B' R'",
    "B' R B' R' B' U B2 U' B' R B2 R'",
    "F R' F' R U2 R U2 B U B' U' R'",
    "B' U' B2 L' B' L2 F' L F L' U' L'",
    "L' F' L U' L' F L U F R' F' R",
    "R B U2 L' U2 L U L' U L B' R'",
    "L U2 L2 B L B' U' B' R' U' R B",
    "L B' U2 B U2 B L2 B2 U' B U L",
    "L' F D2 B' F' U' B U F D2 F' L",
    "B2 L' D' B' U' B D L B2 L' U L",
    "B2 D F' L2 F D' B' U' L U' L' B'",
    "L' B' U' B U' L' D' R B2 R' D L2",
    "R' D F' R2 U L' U' L R2 F D' R",
    "L F2 D R2 F' R2 F R2 F D' F L'",
    "L' R2 D B2 U B U' B D' R2 U2 L",
    "L' D' B R2 D B D' B' R2 B' D L",
    "R B R' F2 D' L' D F2 R U2 B' R'",
    "F' L' U2 F R2 D B' D' R2 F' L F",
  ],
  14: [
    "B' U' R' U R2 B R' U' R' U R",
    "L' U R U' L U B U B' U' R'",
    "R' U F U F' U' R F' L F L'",
    "R B L' B' R' B L2 U L' U' B'",
    "L' U' L B' F2 R' F' R B U F'",
    "L2 F' L' F2 U2 F' U L' B' U' B",
    "L F' L F L U' L2 U L F' L2 F",
    "R U B U' B' U2 R' U2 R' F R F'",
    "R' F R F' U2 R U' R' U2 F' U F",
    "L U L2 B L B2 R B' R' B U B",
    "F' U2 F2 U F2 U F2 U' R U' R' F'",
    "B R B' U B R' B' U' R' F R F'",
    "F' L' U2 B U2 B' U' B U' B' L F",
    "B' U2 B2 L' B' L U L F U F' L'",
    "R B2 R' U2 L U' L2 B' L B' U' B2",
    "F' U2 F R2 U R' F' U' F R U' R2",
    "L F U' R U' R2 F' L F2 R F2 L2",
    "B R' D2 L R U L' U' R' D2 R B'",
    "F' R U' B2 F' L F L' B2 U R' F",
    "F R2 D U B R B' R' D' U' R2 F'",
    "L2 B D L U L' D' B' L2 B U' B'",
    "B' R2 D' F2 R F2 R' F2 R' D R' B",
    "B D L' F2 D' L' D L F2 L D' B'",
    "R B U2 R' F2 D' L D F2 R B' R'",
    "F' L' F R2 D B D' R2 F' U2 L F",
  ],
  15: [
    "B U L U' L2 B L B2 R' U2 R",
    "L' B' R' U R B L U F U2 F'",
    "F U F' U L' B' R' U2 R B L",
    "L U2 L' B2 R B R2 U' R U B",
    "B U2 B2 U' B2 L U' L' B2 U B",
    "B' D' F R' F' D B2 L U L' B'",
    "R' F' U F R' D' L F' L' D R2",
    "F R2 D L B2 L' D2 R D R F'",
    "B' R' U' R U B2 U B' U B U2 B'",
    "B' U2 B U B' R U B U' B' R' B",
    "R' F' U L' U L U2 L' U2 L F R",
    "R B R' F R B' U' B U B' R' F'",
    "B' U2 B U L U' L' B' R' U R B",
    "L B D' L U L' D L' U' L B' L'",
    "F U' F2 D' U' L' U L D F2 U F'",
    "B D' L2 U L U' L2 D B' L' U L",
    "B R U' B2 U' R' U R B2 U R' B'",
    "R' B' D B2 L U L' U' B2 D' B R",
    "F' L' U B2 D' B U' B' D B2 L F",
    "B F2 D' L D F2 R B' U' B R' B'",
    "L' U' L2 F2 R' F D F' D' R F2 L'",
    "F' L2 B2 D' B' D2 L' D' L2 B' L F",
    "R B R' F2 D' L D F2 R B' U' R'",
    "F' L2 D2 B2 D B2 D L' F L2 U L",
    "F U' L D2 B2 U2 R U B2 D2 U' F",
  ],
  16: [
    "L' U' B' U B2 L' B' L2 F U2 F'",
    "B L F U' F' L' B' U' R' U2 R",
    "R' U' R U' B L F U2 F' L' B'",
    "L' U2 L2 U F' D F' D' F2 U' L'",
    "F R U' R' F D B' R B D' F2",
    "L D R' F R D' L2 B' U' B L",
    "R' F2 D' B' L2 B D2 F' D' F' R",
    "L F U F' U' L2 U' L U' L' U2 L",
    "L U2 L' U' L F' U' L' U L F L'",
    "F R U' B U' B' U2 B U2 B' R' F'",
    "B2 R B R' B U B' R' U' R U' B",
    "B' F U' B U F' R B L' B' L R'",
    "F' L' F R' F' L U L' U' L F R",
    "L' U2 L R B U' F U' F' U2 B' R'",
    "B2 D B' U B D' B2 U' B' R B R'",
    "L' R D' B' D L B' U B2 U' B' R'",
    "R' U' R2 B' R F R' B R2 F' U R",
    "L' U' L B D' L2 U L' U' L2 D B'",
    "L' F' U L2 U F U' F' L2 U' F L",
    "L' U' L2 F R' F2 L' F2 R2 U R' F'",
    "R B U' L2 D L' U L D' L2 B' R'",
    "L' R2 D B' D' R2 F' L U L' F L",
    "B U B2 R2 F R' D' R D F' R2 B",
    "R B2 D2 L2 D' L2 D' B R' B2 U' B'",
    "R' U B' D2 L2 U2 F' U' L2 D2 U R'",
  ],
  17: [
    "R B' R' B U2 B U' L U' L' B'",
    "F' L F L' U2 L' U B' U B L",
    "L F U2 F2 U' L' U L F U2 L'",
    "B' R' U2 R2 U B U' B' R' U2 B",
    "R U B L' U' B U L U' B2 R'",
    "R F' U2 B L' U2 L B' U2 F R'",
    "F' R U2 L' B U2 B' L U2 R' F",
    "B L' B' L2 R' F L F' L' F' L' R",
    "L' B L B2 F R' B' R B R B F'",
    "L' U' B U L U' L' B2 U' B U L",
    "B U L' U' B' U B L2 U L' U' B'",
    "F R' F' U B' F R2 B U R U' F'",
    "R' F R U' L R' F2 L' U' F' U R",
    "R B L B U B' L' U B U2 B2 R'",
    "B L' B' L U B F' D L' D' B' F",
    "L' B L B' U' L' R D' B D L R'",
    "L U' F' L F L R D' B D L R'",
    "B' U R B' R' B' F' D L' D' B' F",
    "B U B' R' U L' R2 D B' D' L R'",
    "L' U' L F U' B F2 D' L D B' F",
    "B L U' L' U B2 F D' R D B F'",
    "R2 B2 L' B' L B' R F R F2 U2 F",
    "F2 L2 B L B' L F' R' F' R2 U2 R'",
    "R B U R' F2 D' L' D F2 R B' R'",
    "F' L' U' F R2 D B D' R2 F' L F",
  ],
  18: [
    "B' R' U' R U' B U2 B L' B' L",
    "B L U L' U B' U2 B' R B R'",
    "L F R U2 R' U2 R U2 R' F' L'",
    "R' F' L' U2 L U2 L' U2 L F R",
    "F R U' B U' B' R' F' L' U2 L",
    "R' U2 R B L F U F' U L' B'",
    "L U2 L' B' R' F' U' F U' R B",
    "F' L' U B' U B L F R U2 R'",
    "B U2 B' R' F' U2 F R B U2 B'",
    "R B U2 L' B L B2 R' F' U2 F",
    "F R' F' R U R U' B U B' U' R'",
    "L U F U' R U' R' F' L' B' U B",
    "R' U' F' U L' U L F R B U' B'",
    "F' U' F R B L U L' U B' U' R'",
    "R B U' B2 R B R' U' R' F' U2 F",
    "L' B' U B2 L' B' L U L F U2 F'",
    "B L' B' L2 U L' B' U2 B L U2 L'",
    "L2 R D' B D L R' B' U2 B U L",
    "L F L F2 R' F2 L' R2 U2 R' F' L'",
    "L R2 D F D L R' D' B' D' L2 R'",
    "F R B R2 D2 F L2 D F' D R F'",
    "F' L' B' L2 D2 F' R2 D' F D' L' F",
    "B2 F' L F R2 F2 D2 F L' F R2 B2",
    "L F' D' L D' B2 L' D2 F2 R' F' L'",
    "R' F D R' D B2 R D2 F2 L F R",
  ],
  19: [
    "L U2 F' L' U' L U F2 U2 F' L'",
    "R' U2 F R U R' U' F2 U2 F R",
    "L U2 L' B' R' U F' U2 F R B",
    "R' U2 R B L U' F U2 F' L' B'",
    "R B2 U L' U' B' U L B' U' R'",
    "L' B2 U' R U B U' R' B U L",
    "L' R B R B R' B' L R2 F R F'",
    "L' R B' L' B' L B L2 R' F' L' F",
    "B U L U' L2 B' U' B U L U' B'",
    "B' U' R' U R2 B U B' U' R' U B",
    "L B' R' U' R U B U2 F U2 F' L'",
    "R' B L U L' U' B' U2 F' U2 F R",
    "B U L' U' F' L2 B' F U' B L B'",
    "B' U' R U F R2 B F' U B' R' B",
    "L' R D B D' L R F R F' U' R",
    "L' R D B D' L R' U' B' R B R'",
    "L' R D' B' D L R' U B L' B' L",
    "L' R D' B' D L' R' F' L' F U L'",
    "L' R2 D B' D' L R' U' R' F' U F",
    "R B2 U2 B' U' L B U' B' L' B' R'",
    "L' B2 U2 B U R' B' U B R B L",
    "F R F' L2 D' B D L2 F U' R' F'",
    "F' L' F R2 D B' D' R2 F' U L F",
    "R2 B2 L F' L D2 L2 B2 L F L' R2",
    "L2 B2 R' F R' D2 R2 B2 R' F' L2 R",
  ],
  20: [
    "B F L F2 U2 F2 U2 F2 U2 L' B' F'",
    "L' R' F' L2 U2 L2 U2 L2 U2 F L R",
    "L' R' F' U2 L2 U2 L2 U2 L2 F L R",
    "B F L U2 F2 U2 F2 U2 F2 L' B' F'",
    "B L U L' B' L R2 D' F' D L' R2",
    "B' R' U' R B L2 R' D F D' L2 R",
    "B F2 D' L D B' F2 R B U' B' R'",
    "B' F2 D R' D' B F2 L' B' U B L",
    "B F L B2 U2 B2 D2 F2 D2 L' B' F'",
    "B2 U2 L R' F L2 R2 B D2 B2 L R'",
    "L2 U2 B' F R' B2 F2 L' D2 L2 B' F",
    "B F L D2 F2 D2 B2 U2 B2 L' B' F'",
    "B F' L2 D2 L B2 F2 R B F' U2 L2",
    "L R' F2 D2 F' L2 R2 B' L R' U2 F2",
    "B F L B2 D2 F2 D2 B2 U2 L' B' F'",
    "L' R' F' R2 D2 L2 D2 R2 U2 F L R",
    "B F L F2 D2 B2 U2 B2 D2 L' B' F'",
    "L2 B' F U2 R B2 F2 L' U2 B' F R2",
    "B2 L R' U2 F' L2 R2 B U2 L R' F2",
    "B F L U2 B2 D2 F2 D2 B2 L' B' F'",
    "L' R' F' U2 R2 D2 L2 D2 R2 F L R",
    "B F L D2 B2 U2 B2 D2 F2 L' B' F'",
    "L' R' F' D2 R2 U2 R2 D2 L2 F L R",
    "B2 L' R D2 B L2 R2 F U2 L' R B2",
    "L2 B F' D2 L' B2 F2 R' U2 B F' L2",
  ],
  21: [
    "L U L' U L U' L' U L U2 L'",
    "R' U' R U' R' U R U' R' U2 R",
    "B' U2 B U B' U' B U B' U B",
    "F U2 B F' U' L2 U' L2 U L2 B'",
    "B L2 B2 U2 B L2 B' U2 B2 L2 B'",
    "B' U' B2 L2 D F2 D F2 D2 L2 B'",
    "B U2 B2 R2 F D2 F D2 F2 R2 B",
    "L2 F D2 F' L2 U2 L2 B R2 B' L2",
    "B L' B L B2 R B' R' B R' U2 R",
    "L' U2 L F' L F L' F2 R' F' R F'",
    "L' B' L U2 L U2 L' B U' L U' L'",
    "F U' B' U F2 U' B F U2 F' U' F",
    "R F R2 U' R2 U' R2 U2 R2 U' F' R'",
    "L' F' L2 U L2 U L2 U2 L2 U F L",
    "B L' B' R B L2 U' L' U2 B' U' R'",
    "F R' F' R U2 F2 L' B L' B' L2 F2",
    "F' L F L' U2 F2 R B' R B R2 F2",
    "F' U2 F2 R' D R2 U R2 D' R U' F'",
    "B U2 F2 L2 F U2 F U2 F2 L2 B' F2",
    "B F' L2 B' L2 D F2 U F2 D' L2 F",
    "B D2 U2 B' R2 U2 F L2 F2 U2 F R2",
    "L2 B' U2 B2 R2 B' U2 L2 F D2 U2 F'",
    "B' D' R2 B2 D L2 D2 U' F2 D2 L2 B'",
    "B D' U2 R2 F2 D' L2 U' F2 D2 R2 B",
    "B' D U2 L2 F2 D R2 U F2 D2 L2 B'",
  ],
  22: [
    "R' U L U' R U' L' U' L U' L'",
    "F' U' L' U L F2 R U R' U' F'",
    "R B2 U' B2 U B2 U L R' U2 L'",
    "R' F2 U F2 U' F2 U' L' R U2 L",
    "R U2 R2 D U2 B2 U' B2 D' U' R",
    "R' D U B2 U B2 D' U2 R2 U2 R'",
    "F L' D2 L F' U' F L' D2 L F'",
    "R B2 D2 L2 D' L2 D' B2 R2 U R",
    "L2 R D2 L2 U R2 U L2 D2 L2 R",
    "L U2 L' U2 L' B L' F' L' F L' B'",
    "L F R' F R F L' F U2 F U2 F'",
    "L' B' R B' R' B' L B' U2 B' U2 B",
    "B' U' B U' L B' U2 B U2 B L' B'",
    "R' U2 R2 U' L U2 R2 U R2 U2 L' R'",
    "R B' R2 F' U F U' R2 B R2 U R",
    "R F' U' R2 F U' F' U R2 U F R'",
    "L R' F2 R' D R2 D' F2 D' F2 D L'",
    "F2 R2 B' R' B R' F2 U2 L F' L' F",
    "B L2 F2 D F2 U F' D' F U' L2 B'",
    "F' L2 B2 D' B2 U' B D B' U L2 F",
    "L2 F' D' L2 B L' B' D L2 F U' L'",
    "L U2 L2 B' D2 B L2 U2 F' R2 F L'",
    "L F' R2 F U2 L2 B' D2 B L2 U2 L'",
    "R' D B2 U' R2 F2 U B2 D' L2 F2 R",
    "R' F2 L2 D B2 U' F2 R2 U B2 D' R",
  ],
  23: [
    "L' U R' U L U' R U2 L' U L",
    "R U' L U' R' U L' U2 R U' R'",
    "F L F' U' F L' F' U' L U2 L'",
    "F' R' F U F' R F U R' U2 R",
    "R' D R2 U2 R' U R U R2 D' R",
    "L F' L' B L F2 L' B' L F' L'",
    "B2 R2 D' R' U2 R D R' U2 R' B2",
    "R2 U2 B2 L' B2 L U2 B2 R B2 R",
    "B' D2 F2 D F' R2 F' D2 B' D' B2",
    "F U F2 U' F' L F U F2 U' F' L'",
    "L' R B2 R' U' R U B2 U' R' U L",
    "R B' R2 F R2 B R' F' U2 F' U2 F",
    "F U2 F' L2 B L' B' U2 B' U2 B L'",
    "F U R' F D' F D F2 R2 U' R' F'",
    "L' B' F R2 B L B' R2 B L' F' L",
    "L' D L2 U' F2 U F2 L' U L2 D' L2",
    "R U2 R2 F2 U' F2 D R2 D' R2 U R",
    "F U2 R U R2 D' L F2 L' D R F'",
    "F2 U L U' L2 D F2 D' F2 L U' F2",
    "R' F2 L F' R F2 L2 B' U2 B L F",
    "L R U2 R' F2 U2 L' U2 L F2 U2 L'",
    "R' D' U L2 D R2 D' L2 D R2 U' R",
    "F2 L2 F2 L' U2 R U2 L2 U2 R' U2 L",
    "F D2 L F' L' B' L F L' B D2 F'",
    "L R2 D2 F U F' D2 F U' F' L' R2",
  ],
  24: [
    "F' U L U L' U' F U L U' L'",
    "F U' R' U' R U F' U' R' U R",
    "R U2 F U F' U R' U F U F'",
    "L U F U' L U L' F' L U' L2",
    "R B U' B' U' B L U L' B' R'",
    "F L F' U2 F L' F' U' L U' L'",
    "L' B' U B U B' R' U' R B L",
    "F R U R' F' L' U L F U' F'",
    "L R2 F' R' B' R F R' B L' R'",
    "B F' D' B' D F' D' B D B' F2",
    "L' B' U' R' F' U F U R B L",
    "L B' R2 B' L B R2 B' L' B2 L'",
    "F2 R2 F' D F D' R2 D F' D' F'",
    "B' D2 L D R' D' L' D R D B",
    "L U' B' D2 B U' B' D2 B U2 L'",
    "L2 D R U R' D R U' R' D2 L2",
    "R2 D' L' U' L D' L' U L D2 R2",
    "B L2 B2 F' U2 B F2 U2 F L2 F2",
    "F' L' U' L U L F L' U' L' U L",
    "L' F L F2 L' B L F2 L' B' F' L",
    "R B F' R' F2 R B' R' F2 R F R'",
    "F U2 B' U2 B U2 B' R2 B' R2 B2 F'",
    "F R2 U' L' U B U B' U' L R2 F'",
    "F' L2 U R U' B' U' B U L2 R' F",
    "F' U B2 R B R' U' B2 F L' B' L",
  ],
  25: [
    "F U F' U R' U F U F' U' R",
    "R B U B' U' B2 L' B' L B' R'",
    "L' B' R B' R' B2 U' B' U B L",
    "F' L' U' L U L2 B L B' L F",
    "B L F' L F L2 U L U' L' B'",
    "B2 F2 L' F' R' F L F' R B2 F'",
    "L D R' F2 R D' L' U2 L' U' L",
    "L2 R' U L2 U' R D F2 U' F2 D'",
    "R F' D2 F R' U2 R F' D2 F R'",
    "B' R U R' B R U' R' U' B' U B",
    "L' B' U' B U B L B' U2 B' U2 B",
    "R' F R' F' R2 U R' U' R B U2 B'",
    "B U2 R U2 B U B' R' B' F' U F",
    "F D U' R D R' U R D' R' D' F'",
    "B' D' U L D' L' U' L D L' D B",
    "B L' B2 L2 B U' B' F' L F L2 B",
    "F U F' U2 L' B' U' B L2 F' L' F",
    "L' R B2 R B2 R2 U R U' L U2 R'",
    "B F' L2 F' L2 F2 U' F' U B' U2 F",
    "L' U2 B' F R' U R U' F' U' B L",
    "L' B' L' U2 R' U' L R B L' U2 L2",
    "L' B L B2 F' U R B' R' B2 U' F",
    "R' F' L' R B' R' F R B F' L F",
    "B' U' B' D' F D B D' F' D U B",
    "B U2 F' U B' U' B2 L2 B' L2 B' F",
  ],
  26: [
    "L U L' U L' U' L2 U' L2 U2 L",
    "B U2 B2 U' B2 U' B' U B' U B",
    "R' F R U F' U' F' U L F L'",
    "B' R U R2 U R2 U2 R2 U R B",
    "L R' U' R U R' F2 R' F2 L' R2",
    "L R B' L B R B' L' B L' R2",
    "L2 R' F2 L' F2 L' U L U' L' R",
    "F2 L2 F' U2 F' U' F U' F L2 F2",
    "F R U' R' F' L' B L' B' L U L",
    "L' B L2 B F U F' U' B' L2 B' L",
    "L F2 R2 F2 L' R' U R2 U R2 U' R'",
    "R' B R' D' L D R D' L' D B' R",
    "B U B' U F D' F2 U' F2 D R2 F'",
    "B D F' D' L2 D F2 U' F' D' U B'",
    "R2 U F L2 F' R F L2 F' R' U' R2",
    "L B2 D' L U2 L' D L U2 L' B2 L'",
    "R2 B2 U' R U L U' R' U L' B2 R2",
    "F' L B2 U F2 U' B2 U F2 U' L' F",
    "R U2 R2 F2 D' F2 D' L2 D L2 D R",
    "R' D' F R2 B U B' U' R2 F' D R",
    "R' F' D' L' U' F2 U F L D R F2",
    "B D2 B2 F2 D2 U2 B F2 U' B U' B'",
    "L' D2 U R' U' R2 D B2 D' R' D2 L",
    "L2 R' D2 R2 D2 L2 U R2 U R2 U' R'",
    "R' F2 D R D' L D R' D' L' F2 R",
  ],
  27: [
    "B' U' B U' B U B2 U B2 U2 B'",
    "L' U2 L2 U L2 U L U' L U' L'",
    "B U R' U2 R U R' U R U B'",
    "F U F2 U' F2 U' F2 U2 F2 U2 F'",
    "B' F U F' U' F R2 F R2 B F2",
    "L R' F L F' R' F L' F' L' R2",
    "B' F2 R' B' R F' R' B R B F'",
    "L R2 B' L B R' B' L' B L' R'",
    "L R' F2 R' F2 L' R2 U R' U R",
    "L' U' B U B' L2 B L' U' L B' L'",
    "R' F R2 F U B U' B' F' R2 F' R",
    "L' B' R B' R' B' L' B' L2 F U2 F'",
    "B2 F' L2 F' L2 B' F2 U F' U B' F",
    "L' R B2 U R D' R D R2 U' L R'",
    "R' U L' B' R2 B L B' R2 B U' R",
    "L2 R D' R D' F2 R' D' L D' L R'",
    "L' U' F' U2 F' D' B L2 B' D F2 L",
    "B' U2 B2 F' L2 B D' B' D L2 B' F",
    "F D R' F2 L' U' L U F2 R D' F'",
    "F R D B U R2 U' R' B' D' F' R2",
    "B R2 D L' B2 L D' R' U2 R' U' B'",
    "L' D' B L2 U F U' F' L2 B' D L",
    "B D2 U' F U F2 D' L2 D F D2 B'",
    "F R2 D' F' D B' D' F D B R2 F'",
    "R' F2 L D R D' L' D R' D' F2 R",
  ],
  28: [
    "L R2 F R F' L' R U R' U' R",
    "B' F2 R' F' R B F' U' F U F'",
    "R F R B F' U2 B' F R F' R'",
    "B R B' L R' U2 L' R B' R' B'",
    "L' F' L B' F U2 B F' L F L",
    "R' F' U F U2 F' L' U' L F R",
    "F R U' R' U2 R B U B' R' F'",
    "L U' R B' R' B U L' B U' B'",
    "B' U F' L F L' U' B L' U L",
    "L2 R B L' U2 L B' L' U2 L' R'",
    "L' R' U L U' R F U F' L' U' L",
    "L' R B' R B2 L R' U2 L' B L R'",
    "F U F' L' B' U2 B L U' L' U2 L",
    "B' U2 B R U B' U' R' U2 R B R'",
    "B U L U F' L F L2 B' R' U2 R",
    "B' F' U2 R U2 R' F2 L F2 L' B F",
    "F' D' F' D2 B R' B' D' R F' R' F'",
    "B F' R' F2 D' U L2 D U' R B' F",
    "B2 F D' R D B F' U2 B L U' L'",
    "R U' F' D2 U2 B U B' D2 U2 F R'",
    "F L' B2 D' R' D B' L F' L' B' L",
    "R' B L2 D F D' L B' R B L B'",
    "B2 L2 B' L2 B2 F2 R B R2 F' R F'",
    "F D B' D' R F' D B R' U' R D'",
    "B R F D U' B2 D' U R2 F' R' B'",
  ],
  29: [
    "B' U' R' U2 R U R' U2 R U B",
    "L' B L B' L U2 L' U' B' U' B",
    "B' U2 B2 U B' U' B' U2 R B R'",
    "F R B' R' B F2 U B U' B' F",
    "L' R D B D' R' B U' B' U L",
    "L2 R D' B' D L2 R' U F U F'",
    "L' U2 L F2 R' F2 L F R F' L'",
    "B' U R B' R' F D' R' D B2 F'",
    "B L' D' B2 U' B2 D U L U' B'",
    "L' R B2 R' U' B U B' U' B' U L",
    "F U2 F' L' B' U B L' B L B' L",
    "B L' U' L B' L' U B' R B L R'",
    "B L U' F' U' F2 U' F2 U2 F L' B'",
    "F' U' L' U' L2 U F U' F' L' U2 F",
    "L' B' R B' R' B' L F' L' B' L F",
    "R2 U2 R F R' F' U F' U' F U2 R2",
    "B' U' B U B L2 B2 R B' R' B2 L2",
    "B' F R' F' R B U2 F2 L F L' F",
    "F R' F R D R B' R B R2 D' F2",
    "D L2 D' B R B' D L2 D' B' R' B",
    "L B D R' U' F2 U R D' L2 B' L'",
    "B2 U2 L' B L U2 R2 F R F' R B2",
    "R2 F2 U' F2 D R2 B L' B2 L B D'",
    "R' D2 L2 F' L2 D2 R F R B' R' F'",
    "L2 B2 R2 D' R D F D' F' R B2 L2",
  ],
  30: [
    "B U L U2 L' U' L U2 L' U' B'",
    "R B' R' B R' U2 R U B U B'",
    "B L' B L2 U' L' U' L U L' B2",
    "B U2 B2 U' B U B U2 L' B' L",
    "L' R D' B' D L B' U B U' R'",
    "B U' L' B L F' D L D' B2 F",
    "L' R B2 L U B' U' B U B U' R'",
    "L' U' L B L F' L' F2 U' F' U B'",
    "L F' L2 F U F U2 B' U B F' L",
    "F' U2 F R B U' B' R B' R' B R'",
    "F R F' L' B' F U' B U R' F' L",
    "L2 U2 L' F' L F U' F U F' U2 L2",
    "B F' L F L' B' U2 F2 R' F' R F'",
    "B' U' B L U L2 R D' B D L R'",
    "B F D2 F' U L U' L' F D2 B' F'",
    "R B2 U B' R D B' D' R' B' U' R'",
    "R U2 F R' F R D R' D' F2 U2 R'",
    "R2 U' B U L F U' F' L' B' U2 R2",
    "D' R2 D B' L' B D' R2 D B L B'",
    "B2 U L2 B' D' B D L B L U' B2",
    "R' B' D' L U F2 U' L' D R2 B R",
    "B2 U2 R B' R' U2 L2 F' L' F L' B2",
    "L2 F2 U F2 D' L2 B' R B2 R' B' D",
    "L D2 R2 F R2 D2 L' F' L' B L F",
    "R2 B2 L2 D L' D' F' D F L' B2 R2",
  ],
  31: [
    "F' U' L' U' L U F U2 F' U' F",
    "L U F' U' F L' F' L' U L F",
    "B' F R' F R B F2 U' L' U' L",
    "B' R B R' U B U B' R' U2 R",
    "B2 U' B L U2 L' B' U B U B",
    "L2 R' F R' F D F' D' F' L2 R2",
    "L U2 L2 U' L2 U' L' F2 R' F' R F'",
    "R' U2 R U' B U B2 R B R2 U2 R",
    "R' U' R2 B' R' B' D B' U' B D' B2",
    "R U' B' U2 B U L' D' B D L R'",
    "B' D U' R D' B' D R' D' B U B",
    "F2 R' U2 B' R' B U2 F' L R F' L'",
    "F D U' B2 U R B2 R' B2 D' R F'",
    "B' U' B2 L2 R2 F' D F L R2 B' L",
    "B2 L2 B2 F U R U' R' B2 F' L2 B2",
    "F R B' F D2 B' D2 L' D2 L B2 F2",
    "R B L U2 L' B2 R2 F R2 B R' F'",
    "B U2 B' R2 D' F' L F' L' F2 D R2",
    "R' F R F' U2 F2 D' B L2 B' D F2",
    "R U2 L2 D' B' D L2 F U2 F' U R'",
    "R2 F2 L F' R' D R D' F L' F2 R2",
    "R' F2 D' L D' L' B' L B D2 F2 R",
    "L' U' F R2 D2 B D2 R F' R U' L",
    "R2 F2 L D' F L' F' L D L' F2 R2",
    "L F2 D2 B R B' D2 L' F2 R U2 R'",
  ],
  32: [
    "F U R U R' U' F' U2 F U F'",
    "R' U' F U F' R F R U' R' F'",
    "B F' L F' L' B' F2 U R U R'",
    "B L' B' L U' B' U' B L U2 L'",
    "L U F' U' F L' R B U B' R'",
    "B2 U B' R' U2 R B U' B' U' B'",
    "B' U R B' R' B2 L F U' F' L'",
    "R' F R F' U2 F R' F' R F' U2 F",
    "R' U2 R2 U R2 U R F2 L F L' F",
    "B D' U L' D B D' L D B' U' B'",
    "L U2 L2 U' L2 F' D F' D' F2 U' L'",
    "L U B2 F R B R' U' B2 F' L' B'",
    "L' B L2 F2 L B' L' F L' F2 U2 F'",
    "R B R' F R U2 B' R' F' L' U2 L",
    "B D' B2 U2 R B' R' B U2 B2 D B'",
    "F2 L U2 B L B' U2 F L' R' F R",
    "F' D' U B2 U' L' B2 L B2 D L' F",
    "R' D' L F2 L' D R2 U B U2 B' R'",
    "L F' L' F U2 F2 D B' R2 B D' F2",
    "B' U2 B L2 D F R' F R F2 D' L2",
    "L' B' R' U2 R B2 L2 F' L2 B' L F",
    "L2 F2 R' F L D' L' D F' R F2 L2",
    "R U F' L2 D2 B' D2 L' F L' U R'",
    "L2 F2 R' D F' R F R' D' R F2 L2",
    "R' F2 D2 B' L' B D2 R F2 L' U2 L",
  ],
  33: [
    "B U' B' U' R' U2 R B' R B R'",
    "B' U B U L U2 L' B L' B' L",
    "B' L' B' U B2 U' B2 U' B L B",
    "R' U2 R U B U' L U2 L' U' B'",
    "L2 U' L' U' F U' F' U L U2 L2",
    "B U' L F' L F L' U' L' U2 B'",
    "B' R B R' U' B U2 B' R' U R",
    "L' B' U B U2 L U' F' L F L'",
    "D B2 D' R2 U R2 B R B2 R' B'",
    "B' L' B' L2 U2 L' U B' R' U' R B'",
    "L U2 F R' U' R F' R' U R U2 L'",
    "F2 R' F' L R U L' F2 L F U' L'",
    "R' B' U' F U R2 U' F' U R2 B R",
    "R B2 L2 B' L2 U' F U' F' U2 B' R'",
    "L2 U F2 L' F L F U' L2 F' U F",
    "B2 R D B U B2 D' B2 U' R' U' B",
    "R B' R B2 L' B2 D B' D' L B2 R2",
    "B L' B2 R2 D' R' B' D L B R' B",
    "B L' B' D' R2 D B' L B D' R2 D",
    "B2 L' D' B' D' R2 D R2 D L U B'",
    "L' B2 R B' D B D2 R D R2 B2 L",
    "L2 D R' F' R' D' F' D F R2 D' L2",
    "R2 D' L F L D F D' F' L2 D R2",
    "R2 B2 L' D L B' L' B D' L B2 R2",
    "L2 B2 R D' R' B R B' D R' B2 L2",
  ],
  34: [
    "L U L2 U' L' B L U L U' B'",
    "R' U' R2 U R B' R' U' R' U B",
    "B' U2 B2 U L U' L2 B' L2 U' L'",
    "R' U' L' R2 B D B D' B2 L R'",
    "F2 D F' U F D' R' F' R U' F'",
    "F2 D' F U' F' D L F L' U F",
    "F R2 D B2 R D2 F L D F2 R",
    "B U B' L' B2 U B U' B' U' B' L",
    "F U F' R' F R U' F' U2 F' U2 F",
    "F' U' F L F' L' U F U2 F U2 F'",
    "L' R B L U L' U' B' U L U' R'",
    "L' R B' R' U' R U B U' R' U L",
    "L' R U R B U B' U' L R' U' R'",
    "R' F' U F U F' U' L F' L' F2 R",
    "F' L' U' L F' U B U' F U B' F",
    "B F U2 F' L U L' U' F U2 B' F'",
    "B' U' B U2 L2 U F U' F2 L' F L'",
    "F R U B R' F R B' R' F' U' F'",
    "F' L' U' B' L F' L' B L F U F",
    "R U' B' R2 F' R' B R' U' R2 F R",
    "B' F' D2 B L' U' L U B' D2 B F",
    "F2 L2 F' R2 F L2 F' R' U R' U' F'",
    "R2 B2 U' R2 U B2 R2 B R B2 R' B'",
    "R U2 F D R D' F2 U2 F R U' R2",
    "B2 L2 F R' D' R D F D' F2 L2 B2",
  ],
  35: [
    "L U2 L' U' F' L F U' F' L' F",
    "B' U2 B U R B' R' U R B R'",
    "L2 R2 B D2 B' L' R F2 L' F' R",
    "B2 F2 L' D2 L B F' R2 B R F'",
    "F2 U' F' R U R' U' F' U F2 U F2",
    "R2 U R F' U' F U R U' R2 U' R2",
    "F R' F' R' F2 R2 U R U' R F2 R2",
    "R' F R F R2 F2 U' F' U F' R2 F2",
    "L U F' L F L' U2 R' U L' U' R",
    "B' U' R B' R' B U2 F U' B U F'",
    "F U2 F2 L2 B F L B' L B' U2 B",
    "R' U2 R2 B2 L' R' B' L B' L U2 L'",
    "B' F2 R B' F' R2 F R F' R2 B2 F'",
    "L2 R' F2 L' R' F L F' R F2 L2 R",
    "F U2 L2 D F D' F' L' F L' U2 F'",
    "F R' D B2 R B2 R' U' B2 D' U F'",
    "R' F D' L2 F' L2 F U L2 D U' R",
    "L2 R' B R' D2 R B' L' F2 L' F' R",
    "L2 R2 D2 R D2 L2 F R F' R U2 R'",
    "B2 F2 D2 F' D2 B2 R' F' R F' U2 F",
    "F R D2 L' U F2 U' L D R2 D F'",
    "R' F' D2 B U' R2 U B' D' F2 D' R",
    "F R B R' F' R' D2 L2 F L2 D2 R",
    "R' F' L' F R F D2 B2 R' B2 D2 F'",
    "R B2 L D2 L B R2 F R B2 L2 B'",
  ],
  36: [
    "L U L' U' B' U2 B U L U L'",
    "R' U' F' U2 L' U' L U' F U R",
    "R' F' L F2 R' F L' F' R F' R",
    "B U B' R' U F' L' U' L F R",
    "F' D' B L' B' D F U' L' U2 L",
    "F' R' D' F' D L R F' L' U F2",
    "B L2 D F L D2 B R2 D B2 L",
    "F' U' F2 R' F' R2 U R' U' R U' R'",
    "F' U2 F2 U R U' R' F' U' F' U2 F",
    "L F R U2 R' U2 F' L F' L' F L'",
    "B R' U R B U' L U2 L2 B L B",
    "R2 U' R' F R F' U R2 U2 B U' B'",
    "R2 F' R U' L' U R' F R2 F' L F",
    "F' R U' B2 L' U L U' B2 U R' F",
    "L B2 F R2 F R2 B F2 U2 B U2 L'",
    "L2 B2 L' U F U' F L B2 L' F2 L'",
    "F' L2 B' R' F U2 F' R B2 L' B' F",
    "L' U F' U2 F R2 D B' D' R2 U2 L",
    "B D2 F2 D2 L' B' L F L2 F2 L2 F'",
    "B2 D L2 F' L' F L' D' B2 R' U2 R",
    "B L2 D2 R F R' F' D' F D' L2 B'",
    "B' F2 R F L2 F L F2 R' B D2 F2",
    "L R2 D2 L' R2 F' L F R2 D2 L' R2",
    "B L' B D2 L' F R F' L D2 B2 L",
    "R' U2 R B2 L' D2 F' R F D2 B2 L",
  ],
  37: [
    "B U L' U' L' B' L U L2 U' L'",
    "L' U' B U B L B' U' B2 U B",
    "L2 U2 L' U' F U F' U L U L2",
    "L' B L B' U' L U2 F U F' L'",
    "F U2 F' L' U L U F' L F L'",
    "R' U F U R' F R F' U' F' R",
    "R' U2 R B U' B' U' R B' R' B",
    "R' U' R' U' R B U2 B' R' U R2",
    "F U F U F' L' U2 L F U' F2",
    "L R' F U' F' L' B' U B U R",
    "L' R B2 D B' D' B' L R2 U R",
    "B L F2 R' F' R F' U2 L' U2 B'",
    "F R' F R F' R U2 R' F' L' U2 L",
    "L' B' U' B' D' B' D B' U L2 U2 L'",
    "L U' L' U2 B' R2 F R F' R U' B",
    "F' L D L' U' L D' F' L' F U F",
    "B F2 D' L' D F2 U' R U' R' U2 B'",
    "L2 R D' B D L2 R' U' F' L F L'",
    "B2 D L' F L U' L' F' L D' U B2",
    "L2 D' B R' B' U B R B' D U' L2",
    "B2 D B2 U L U B' U2 B2 L' D' B'",
    "L' U F D' R2 D F' U2 B U B2 L",
    "B L2 F' L B L' F L2 B2 R' U2 R",
    "L2 U2 F2 D F D' L' F U L U L2",
    "B2 U2 R2 D' R' D B R' U' B' U' B2",
  ],
  38: [
    "F U F' U F U2 R U R' U' F'",
    "B' U' B U L U2 L' U' B' U' B",
    "B L U' L' U L F U F' L' B'",
    "F R B' R2 F R' B R F' R F'",
    "R D L' B L D' R' U B U2 B'",
    "R F D R D' B' F' R B U' R2",
    "L' B2 D' R' B' D2 L' F2 D' L2 B'",
    "R U R2 F R F2 U' F U F' U F",
    "B' R B' R' B2 L U' L' U L U2 L'",
    "R U2 R2 U' F' U F R U R U2 R'",
    "L' B' U' B L B L' U L2 U' L' B'",
    "F R' F R F' R U2 B U2 B' R' F'",
    "F2 U F R' F' R U' F2 U2 L' U L",
    "R' F2 R2 B' R B R2 F2 U F' U F",
    "B L B' U2 F L2 F2 L' F2 L' F' L'",
    "F U2 F' L D' L B L B' L' D L2",
    "B' F2 D R' D' R' D R2 D' R' B F2",
    "B2 L2 B U' R' U R' B' L2 B R2 B",
    "R B2 L F R' U2 R F' L2 B L R'",
    "B U' R U2 R' F2 D' L D F2 U2 B'",
    "L' D2 R2 D2 B L B' R' B2 R2 B2 R",
    "L2 D' B2 R B R' B D L2 F U2 F'",
    "L' B2 D2 F' R' F R D R' D B2 L",
    "L R2 F' R' B2 R' B' R2 F L' D2 R2",
    "L' B L' D2 B R' F' R B' D2 L2 B'",
  ],
  39: [
    "R' F' U' F R F R' U R U' F'",
    "F U' F' U' L2 R B L B' L R'",
    "R B U' B' R' U' R2 B' R' B R'",
    "F R' F R F2 U F R U R' F'",
    "R' U2 B U2 F' U' F U2 B' U' R",
    "B L F U R U R' F' L' U' B'",
    "L2 R2 F D F D' F' R F' L2 R",
    "L' U' L B L' B' U L U L U' L'",
    "L U L' U L U' L2 B L B2 U B",
    "F R' F' R U R B' R B R' U' R'",
    "L' B' U' B U L2 U2 L' U' L U' L'",
    "L' U L2 U F U' F' L' U L' U2 L",
    "R' U2 R U2 R U B' R' B R U' R'",
    "B' U' B L U2 L' U' L2 F' L' F L'",
    "B L F U' F' L' U L U2 L' U' B'",
    "R' F' U' F2 U' B' U F' U' B U2 R",
    "L2 R' F' D' L D L2 U' F U L' R",
    "F2 L D' F U F' D L' F2 L U' L'",
    "L2 D' L' D2 R' F' R D' F L' U' F'",
    "B2 U B' R' U2 R2 D B' D' R' U2 B'",
    "R U B2 D F' L2 F D' B' U B' R'",
    "R2 D2 B' U B U' B L B' L' D2 R2",
    "R2 U B' R' B R2 U2 L' D B2 D' L",
    "R' U L' B L' D2 F' D2 L2 B' U R",
    "B D' L2 D B' U2 F2 L F' L' U F2",
  ],
  40: [
    "F R U R' F' R' F U' F' U R",
    "R' U R U B2 F' L' B' L B' F",
    "F U2 L' U2 R U R' U2 L U F'",
    "L' B' R' U' F' U' F R B U L",
    "B2 F2 R' D' R' D R F' R B2 F'",
    "L' B D L' D R F R' D2 L2 B'",
    "B U B' L' B L U' B' U' B' U B",
    "B' U' B U' B' U B2 L' B' L2 U' L'",
    "R' F R F' U' F' L F' L' F U F",
    "B U' B2 U' R' U R B U' B U2 B'",
    "B' R' U' R U R' F R B R' F' R",
    "B L2 F' L' F U' L' U L U L' B'",
    "B' R' U F' U' B F L' B' R B L",
    "R' U' F' U2 F R B2 L' B' L U' B'",
    "L2 B' L F' L' B U' L2 U L' F L",
    "B D U B D' L' D B' D' L U' B'",
    "R2 U' R B F' L U L' B' U' F R",
    "B2 F R D B' D' B2 U R' U' B F'",
    "F U R F D R D' F' R U' R2 F'",
    "R2 B' D R' U' R D' B R2 B' U B",
    "B2 D B D2 F R F' D R' B U R",
    "L2 U' L F U2 F2 D' L D F U2 L",
    "F2 D2 L U' L' U L' B' L B D2 F2",
    "F U' B L' B D2 R D2 B2 L U' F'",
    "L' D B2 D' L U2 R2 B' R B U' R2",
  ],
  41: [
    "R U' R' U2 R U B U' B' U' R'",
    "F R B F' L' B L B2 F R' F'",
    "L' U2 L U F' D' B L B' D F",
    "L' F R2 B2 R' B R B R2 F' L",
    "F R U' R' B F2 D' L D B' F",
    "L' B' R D L B L' D' B L R'",
    "L U F U' L2 D2 R2 B R2 D2 L",
    "L' B L B' U2 B U B2 U B2 U2 B'",
    "B R U' L U L' U R' B' R U' R'",
    "R U2 L R2 F' L' F2 R F R' F2 R",
    "R U R U R' F D R' D' F' U2 R'",
    "B U2 R D B D' R' B U' B' U' B'",
    "B' L' B2 U' B U R B2 L B' R' B2",
    "B U2 L' D' L U' L' D L2 U' L' B'",
    "L' B L2 F2 L B' L' F2 L' F U2 F'",
    "R D L2 D' B' D B L B' L D' R'",
    "B' U2 F R U F R F' U' R' B F'",
    "B2 F R2 B F' R U2 R2 U2 R' U2 B",
    "L' R2 D B2 D' L R' B U' B' U' R'",
    "B L2 U L U2 R' D F2 D' R U B'",
    "F U2 B' F' U2 L2 B2 L B2 L U2 B",
    "L2 D2 R' F L2 B' L' B2 L' F' L2 R",
    "B2 L2 R2 F' D L' F L' R2 B' U' B'",
    "F U F L2 R B' R D' B L2 R2 F2",
    "F R2 F2 L' B' L2 F' R' D2 R' F2 L'",
  ],
  42: [
    "L' U L U2 L' U' B' U B U L",
    "F' L' B' F R B' R' B2 F' L F",
    "R U2 R' U' F D B' R' B D' F'",
    "R F' L2 B2 L B' L' B' L2 F R'",
    "F' L' U L B' F2 D R' D' B F'",
    "R' U' F' U R2 D2 L2 B' L2 D2 R'",
    "R B' R' B U2 B' U' B2 U' B2 U2 B",
    "B' U2 B U B' U B2 L U L' U' B'",
    "B' L' U R' U' R U' L B L' U L",
    "B' R B' R2 U' R U B2 U2 L U' L'",
    "L' R2 B2 L R' U B' U' B U B R'",
    "L' U2 L2 R' F R F2 L' F' L F2 L'",
    "B' F2 R F D' F' D R' F' R' B F'",
    "B R B2 U B' U' L' B2 R' B L B2",
    "L U L' B' U2 B2 F' D L' D' B' F",
    "R B' R2 F2 R' B R F2 R F' U2 F",
    "L' D R2 D B D' B' R' B R' D' L",
    "B U2 F' L' U' F' L' F U L B' F",
    "B2 F' L2 B' F L' U2 L2 U2 L U2 B'",
    "L2 R D' B2 D L R' B' U B U L",
    "L' B' U B U L2 D R' F' R D' L'",
    "B2 L2 R2 F D' R F' L2 R B U B",
    "R2 D2 L F' R2 B R B2 R F L' R2",
    "F' L2 F2 R B R2 F L D2 L F2 R",
    "B' U2 R D2 L2 D2 R D2 F' L2 D2 R2",
  ],
  43: [
    "R U' R' U' F' U2 F U R U' R'",
    "B' U' B U B U L' U' B' U L",
    "B' F R' F' R U R U' R' U' B",
    "L U L' B' U' B U' L' B L B'",
    "L F' L' F U L' U L F U' F'",
    "F' L' F U2 F2 L2 B L B' L2 F2",
    "R' F2 L2 D' B D' B' D2 L2 F2 R",
    "R B F L F' U F L' B' F' U' R'",
    "L2 B' U B U' B' U' R B' R' B2 L2",
    "B L' B' L2 F2 R' F' R2 U2 R' F' L'",
    "F D' F2 U2 F' L F L' U2 F2 D F'",
    "R B L' D' L U2 L' D L B' U2 R'",
    "F D' R' D F D' R D F2 L' U2 L",
    "R' F U2 L F' L' U2 F' R2 B' R' B",
    "R2 B' F2 D' B' D B D F2 R' B R'",
    "R2 B2 L' B R' B' L B2 R2 F R F'",
    "B' F R' B2 L F' U2 F L' B' R2 F'",
    "R2 D B' L R' U L' U' R B D' R2",
    "L2 R2 D2 L' D2 L2 R2 U B' U B L",
    "R2 D2 U2 L U' B' U B L' D2 U2 R2",
    "R' D2 U B2 F2 D2 U2 B2 F U F R",
    "L2 B2 F2 R' D F D' F' R B2 F2 L2",
    "F R2 F2 L2 B D2 B' L' F' R2 F2 L'",
    "F R2 B2 R F L D2 L' F2 R2 B2 R'",
    "R2 D2 L2 F D2 R' D2 L2 D2 R' U2 B",
  ],
  44: [
    "L' U L U F U2 F' U' L' U L",
    "B U B' U' B' U' R U B U' R'",
    "B F' L F L' U' L' U L U B'",
    "R' F R F' U' R U' R' F' U F",
    "R' U' R B U B' U R B' R' B",
    "F U F2 L F L B L B' U L",
    "L F R U2 B U B' R' U F' L'",
    "F R F' U2 F2 R2 B' R' B R2 F2",
    "L2 R U' L B' U' B U L' R' U L2",
    "L U F' U B U' F2 U B' U2 F' L'",
    "F R2 D R D' R F L F L' U F",
    "B2 D L' F' L B' L F L' B D' B2",
    "B' R2 B2 U' R' F R F' U B2 R2 B",
    "F D R F2 U' F U' R' U2 F2 D' F2",
    "L2 R2 D2 R D2 L2 R2 U' B U' B' R'",
    "L' B' U2 B U L2 D R' F2 R D' L'",
    "L' B F' L2 B D2 B' D2 F L2 B' L",
    "L U F U' B2 F L2 R2 B2 F2 L R2",
    "F2 L2 R2 B' D B L2 R F' R U' F'",
    "L2 D2 U2 R' U B U' B' R D2 U2 L2",
    "B L2 F2 D R F' R' F D' F2 L2 B'",
    "R2 B2 F2 L D' F' D F L' B2 F2 R2",
    "L U B2 F' D2 U2 B2 F2 D2 U F' L'",
    "F' L2 F2 R2 B' D2 B R F L2 F2 R",
    "F' L2 B2 L' F' R' D2 R F2 L2 B2 L",
  ],
  45: [
    "R2 B U' B' U B U B2 R' B R'",
    "R D' B U B' U' R' U' R D R'",
    "L' D B' U' B U L U L' D' L",
    "L U L2 B L2 U L' U' B2 U2 B",
    "R' U' R2 B' R2 U' R U B2 U2 B'",
    "R' U' B F2 L F L' B' F U R",
    "L U B' F2 R' F' R B F' U' L'",
    "R' D' R' D B R2 U R B' U' R'",
    "L' U' L' B2 D' B' D L B' U L",
    "R2 B R2 U F R' F' R2 B' U' R'",
    "B U' L' U L U B' F2 R' F' R F'",
    "R2 U' L R U' F' U F R' U L' R2",
    "L F2 D F D' F2 U F' U' L2 U2 L",
    "L' R F2 L B U B' U' L' F2 L R'",
    "L U2 F R2 U B U' B' R2 U2 F' L'",
    "L2 D2 U2 R F' U' F U R' D2 U2 L2",
    "L2 R' B2 F2 L2 R2 B' F2 U B' U' R'",
    "L' B' U' B' F2 D2 U2 B2 F2 D2 U' L",
    "R B U B' U' L2 R D2 U2 L2 R2 D2",
    "D2 L' B' U' B U L' R2 D2 U2 L2 R2",
    "D2 L2 R2 D2 U2 L' R2 F U F' U' L'",
    "L R2 F' D' F R2 B2 L2 U' L2 B2 L'",
    "L' R2 D2 L2 F L2 D2 R2 U' B U L",
    "R2 B2 F2 L' B D B' D' L B2 F2 R2",
    "R B D2 U' B2 F2 D2 U2 B F2 U' R'",
  ],
  46: [
    "B U L' U' B' U L U L U' L'",
    "B' U' R U B U' R' U' R' U R",
    "L F' L F L' U' L' U2 B' U B",
    "L' F' L' U L U F R U' L R'",
    "B L U L2 U' L B' U' L' U2 L",
    "B' R' U' R2 U R' B U R U2 R'",
    "F U R U' R B' R2 F' R B R'",
    "F R F' U' R B U B' R' U' R'",
    "F' L' F U L' B' U' B L U L",
    "F R B' R' F' U' R U B U' R'",
    "B' F U R F R' F' U' R' B F'",
    "R' U' R B U2 L F U F' L' B'",
    "R U F' U' F U F R' F' R U2 R'",
    "R B' R' B' U' B R B' U B2 U' R'",
    "R2 B2 R U' R U R2 B2 R' B' R' B",
    "R' B' F R' B U R D R D' U' F'",
    "F2 D' B L B' L U' L' U L' D F2",
    "R D' R2 U' R2 D B L' B2 L B R'",
    "F R2 B F2 L U' L' U B' F2 R2 F'",
    "F2 R2 F L F' R2 F L2 U' L U F",
    "F2 D F' R B' R' F R' B R D' F2",
    "B2 D F' L2 F D' B2 U2 B' R B R'",
    "F2 L2 B L' B' D' B L B' D L2 F2",
    "F2 R2 B' R B D B' R' B D' R2 F2",
    "F' L2 B2 D2 R D R' B' D B' L2 F",
  ],
  47: [
    "B' R B U2 R' U' R U' R2 U2 R",
    "B' F' U2 F R2 B2 L' B R2 B2 L",
    "B L' B L B R B R' U R' U R",
    "L' U' L' B L B' L' B L B' U L",
    "B L U' L' B' R' U' R U R' U R",
    "L' U' L U' L' U2 L2 F U F' U' L'",
    "L' B' U R' U' R U R' U' R B L",
    "R U R2 F R F' L F' U F U' L'",
    "B U B2 R B R2 U F' U' F U R",
    "B' R' U' R U B F R U R' U' F'",
    "B U B' U R2 F R F2 U' F U R",
    "R' F R B' R2 F' R F R' F' R2 B",
    "R U2 B U2 B U2 B2 U' B2 U' B2 R'",
    "L' B2 R B' L B2 R' B' R B R' B",
    "B' U2 B L' B L U B2 U B2 U2 B'",
    "B' R B2 L U' L' U2 B' U' R2 U2 R",
    "B L2 D L D2 B D B U' B U L",
    "B' R2 F R' D R D' R2 B R' F' R",
    "B' R2 F2 R F2 R U F U' B U2 F'",
    "F U2 F2 L F2 R F' L' F R' U2 F'",
    "L2 F2 L2 F' U2 B F L' B' L2 F2 L'",
    "R B' L2 B' D B D' L2 B R2 U R",
    "L2 D R' F2 R D' L2 B2 R B R' B",
    "F D2 B2 R B R' D' B2 D' F' U R2",
    "L' B2 R2 D' R' B' D L B2 R' U B",
  ],
  48: [
    "F R' F' U2 R U R' U R2 U2 R'",
    "B F U2 B' R2 F2 L F' R2 F2 L'",
    "F' L F' L' F' R' F' R U' R U' R'",
    "L U L F' L' F L F' L' F U' L'",
    "L U L' U L U2 L2 B' U' B U L",
    "L F U' R U R' U' R U R' F' L'",
    "R' U' R2 B' R' B L' B U' B' U L",
    "F R U R' U' B' F' R' U' R U B",
    "L' B' U B L F U' R U R' U' F'",
    "F' U' F U' R2 B' R' B2 U B' U' R'",
    "R B' R' F R2 B R' B' R B R2 F'",
    "L F2 R' F L' F2 R F R' F' R F'",
    "F U2 F' L F' L' U' F2 U' F2 U2 F",
    "F' L2 D' L' D2 F' D' F' U F' U' L'",
    "F R2 B' R D' R' D R2 F' R B R'",
    "F R2 B2 R' B2 R' U' B' U F' U2 B",
    "F U F2 L' F U2 L2 B L2 B' U' L",
    "B' U2 B2 L' B2 R' B L B' R U2 B",
    "L2 B2 L2 B U2 B' F' L F L2 B2 L",
    "L2 B2 L' F R' F L R B2 L' F2 L'",
    "R' F L2 F D' F' D L2 F' R2 U' R'",
    "L2 D' R B2 R' D L2 F2 R' F' R F'",
    "B' D2 F2 R' F' R D F2 D B U' R2",
    "L F2 R2 D R F D' L' F2 R U' F'",
    "L2 F2 R2 B' D2 B F L' F' R2 F2 L'",
  ],
  49: [
    "R' U' R2 B' R' B U' B' R B R'",
    "L U F U2 F' U2 L' U' B' U2 B",
    "B' U2 B U L U2 F U2 F' U' L'",
    "F R U R' U' F2 U' L' U L F",
    "R' F R' D R' D' R2 F2 U' F R",
    "R U2 L' R' F' U2 B' U2 B F L",
    "F' D' L U' L U L' D F2 U2 F'",
    "F2 R2 F' R2 F2 L F L' R' U2 R",
    "L F' L2 B' F2 R2 F R2 B F2 L",
    "L B' U2 F R' U R F' U2 B L'",
    "B' L U2 R' F U F' R U2 L' B",
    "L B2 F R2 B R2 B2 F' L2 B' L",
    "F U2 F' U' L2 D' R B' R' D L2",
    "L U L' U L U' L' B' R' U' R B",
    "R' F' L' F R F' L U' L' U L F",
    "B U2 B2 U' B2 U' L' B' L B' U2 B",
    "F2 U' F L F' U F U' L2 U L F",
    "L' B2 L2 B' U2 B2 U2 B L' R' U2 R",
    "F U2 B' U F' U' R' F2 R' F2 R2 B",
    "L2 B2 L' F2 L B2 L' R' F' R F' L'",
    "B L F' L B2 U2 B F2 U2 F L2 F2",
    "F2 U' L D R2 D F R' F' R2 D2 L'",
    "L R2 D2 B2 L2 B L2 B D2 R2 F' L'",
    "L' F2 D2 B D2 F L2 D2 B' D2 F L'",
    "L' B D2 F' D2 L2 B D2 F D2 B2 L'",
  ],
  50: [
    "R U R2 F R F' U F R' F' R",
    "L' U' B' U2 B U2 L U F U2 F'",
    "F U2 F' U' L' U2 B' U2 B U L",
    "B' R' U' R U B2 U L U' L' B'",
    "R B' R D' R D R2 B2 U B' R'",
    "R' U2 L R B U2 F U2 B' F' L'",
    "B D L' U L' U' L D' B2 U2 B",
    "B2 R2 B R2 B2 L' B' L R U2 R'",
    "L' F2 L2 B L2 B' F2 L R U2 R'",
    "L' B L2 B2 F R2 B' R2 B2 F' L'",
    "F L' U2 R B' U' B R' U2 L F'",
    "L' F U2 B' R U' R' B U2 F' L",
    "B L' B' R B2 D L' D' L2 B2 R'",
    "B' U2 B U L2 D R' F R D' L2",
    "F R' F R F' R U' B U2 B' R' F'",
    "B' U F U' B U2 R' F R F' U' F'",
    "R B L B' R' B L' U L U' L' B'",
    "B L2 U L2 B' L B L U' L B' L",
    "F U2 B' R B R' F' R' F2 R' F2 R2",
    "R' F' L F' L' F2 R2 U B U' B' R'",
    "L F2 L2 F U2 F2 U2 F' L R U2 R'",
    "L2 F2 L B2 L' F2 L R B R' B L",
    "F' L' B L' F2 U2 B2 F' U2 B' L2 B2",
    "B2 U L' D' R2 D' B' R B R2 D2 L",
    "L F' D2 B D2 L2 F' D2 B' D2 F2 L",
  ],
  51: [
    "B U B L' B' L B' U B U2 B'",
    "F' U' F' L F L' F U' F' U2 F",
    "L F' L F L' U' L' U B' U2 B",
    "B' U2 B U' L U L F' L' F L'",
    "F U R' U' F' U R U2 R U2 R'",
    "B' U' R U B U' R' U2 R' U2 R",
    "L' F L U' R U2 R' U L' F' L",
    "R' U2 R U2 R B' R2 U' R U B",
    "B' U F' R' F U2 F' R F U' B",
    "F U' B R B' U2 B R' B' U F'",
    "F2 D B' R' B D' F2 U' L' U2 L",
    "B2 D' F R F' D B2 U L U2 L'",
    "L' B U B2 U B2 U' L U' L' B' L",
    "L' U' L2 U L F' L2 F U L U2 L'",
    "B' U2 B U R B2 R' B U B2 U' B'",
    "R' U' R2 B L' B L B2 R' B U' B'",
    "L F U' R' F R F2 L' U B' U2 B",
    "F U F2 L F2 U F' L2 U L2 U2 L'",
    "L2 U L U' F' U' L' U L2 F2 U2 F'",
    "F U2 B' R' U' R2 U R F R2 B F2",
    "B' U2 B2 L2 U L' U' L2 D L D' B'",
    "B' U2 B2 F' L D L2 D' L' B' L2 F",
    "F' U' L2 D' L U L2 D L' F2 U' F'",
    "B L2 F' L' D' L2 D L B' F2 U2 F'",
    "B D F2 D F2 D' L' D' L B2 U2 B",
  ],
  52: [
    "L' U' B' U2 B U2 B' U2 B U L",
    "L U F U2 F' U2 F U2 F' U' L'",
    "R U B U' B2 R' B U2 B U2 B'",
    "R' U' F' U F2 R F' U2 F' U2 F",
    "R U2 R2 D' F U' F' U F' D R",
    "R' U2 R2 D B' U B U' B D' R'",
    "L U L' U L' B L B R B R' B",
    "L' U' L U' L F' L' F' R' F' R F'",
    "R' F' U' F2 U F' U F U2 F' U' R",
    "R B L U' L' U L U' L' U B' R'",
    "L' U' B' U B2 L' B' L2 U' F U' F'",
    "B L U L2 B L B2 U' B' R B R'",
    "L F2 U F2 U F2 U2 F' U2 F' U2 L'",
    "L R2 D' F' D F' R F R' F L' R2",
    "L' R2 D B D' B R' B' R B' L R2",
    "L2 R B' L B' L' B D' B D L2 R'",
    "L2 R' F L' F L F' D F' D' L2 R",
    "L2 R B' D' B D' R D R' D L2 R'",
    "L' R2 D L' D L D' B D' B' L R2",
    "F R' F D' F D F2 R2 U2 R' U' F'",
    "B' R B' D B' D' B2 R2 U2 R U B",
    "R B U B2 R2 D' R' D B R' U' R'",
    "R' U2 R2 B' D B D L2 D' L2 D' R'",
    "L U B L2 F' L2 B' F2 U2 F' U' L'",
    "R U B' R2 F D R' B' D' B2 R2 F'",
  ],
  53: [
    "R' F' L F' L' F L F' L' F2 R",
    "B' R B R' U' R B' R' B2 U' B'",
    "B' R2 F R F' R' F R F' R B",
    "R B U' B2 R2 D' R' D R' B R'",
    "B R' U' F' U R B2 R' F R B",
    "B' U' B L U' L' U' L2 F' L' F L'",
    "L' U R U' L U' R' U2 R' F R F'",
    "R' F' U' F2 U R U' F' U2 F' U2 F",
    "L U F' U' F L' F R' F' R2 U' R'",
    "L U2 L' B' R' U' R B' R B R' B",
    "F' U2 F U2 F U R' U' F2 U F R",
    "F R B U2 B' U R' F R' F' R F'",
    "F R' F R F2 R U' L' U R' U2 L",
    "L R' U' R U L' U2 B2 L' B' L B'",
    "B U' L' B L B2 U' B2 L' B' L B'",
    "B' U R' U' R B U L2 F' L' F L'",
    "R' U F' U2 F2 R' F' R2 U2 B U B'",
    "F2 U2 L F L' F2 U' F2 U' F' U2 F'",
    "B U2 F' L' B L B2 F U' B U' B'",
    "L' U' L U' L2 R B L B' R' U2 L",
    "R' U2 R2 U R2 F' U F2 R F2 U F",
    "R' U' R2 B U B2 D B' D' B2 U' R'",
    "F' L U2 B L' B2 U2 B L2 F' L F2",
    "B' R2 B' F R D2 R D2 R' D2 B2 F'",
    "F R B2 D2 L' F2 L' F2 L2 D2 B2 F'",
  ],
  54: [
    "R B L' B L B' L' B L B2 R'",
    "F R' F' R U R' F R F2 U F",
    "R' F' U F2 R2 D R D' R F' R",
    "F U F' L' U L U L2 B L B' L",
    "L U' R' U L' U R U2 R B' R' B",
    "R B U B2 U' R' U B U2 B U2 B'",
    "L' U' B L' B' L2 B L' U L U' B'",
    "B U2 B' U2 B' U' R U B2 U' B' R'",
    "B' R' F' U2 F U' R B' R B R' B",
    "L' R U R' U' L U2 F2 L F L' F",
    "B' R B' R' B2 R' U L U' R U2 L'",
    "F' U L F' L' F2 R' F R F2 U F",
    "F U' R U R' F' U' L2 B L B' L",
    "R U' B U2 B2 R B R2 U2 F' U' F",
    "B2 U2 L' B' L B2 U B2 U B U2 B",
    "L U L' U L2 R' F' L' F R U2 L'",
    "F' U2 B L F' L' B' F2 U F' U F",
    "R U2 R2 U' R2 B U' B2 R' B2 U' B'",
    "B U' L' F U' F2 L F2 U F' L B'",
    "B U R' U2 R B2 L' B2 L2 U' L' B'",
    "R B U B2 R2 B R2 F' U2 F U' R'",
    "R U R2 F L2 D' F D F' L2 F' R",
    "B L' U2 F' L F2 U2 F' L2 B L' B2",
    "F R2 B' F R' D2 R' D2 R D2 B F2",
    "B' R' F2 D2 L B2 L B2 L2 D2 B F2",
  ],
  55: [
    "L U2 L2 U' L U' L' U2 B L B'",
    "R' U2 R2 U R' U R U2 B' R' B",
    "R B U' L U L2 B' R' B L B'",
    "L' B' U R' U' R2 B L B' R' B",
    "L D' L2 U B' U2 B U' L2 D L'",
    "L' D L2 U' F U2 F' U L2 D' L",
    "L U' F2 D F' U2 F D' F2 U L'",
    "L' U B2 D' B U2 B' D B2 U' L",
    "R B2 L2 D L D' B2 R' B L B'",
    "L' B2 R2 D' R' D B2 L B' R' B",
    "B L' U' B' U B2 L B2 U' B U B'",
    "F' L U F U' F2 L' F2 U F' U' F",
    "B L' B U' B L B L' B2 U B2 L",
    "B L' U' L2 U' L2 U2 B L B' U' B'",
    "F' L F' U F' L' F' L F2 U' F2 L'",
    "B' R U R2 U R2 U2 B' R' B U B",
    "R' U2 R2 U B U2 L U L' B2 R' B",
    "L U2 L2 U' B' U2 R' U' R B2 L B'",
    "B L2 F' L' B' F2 U F' U' B L' B'",
    "B' R2 F R B F2 U' F U B' R B",
    "R B2 L' D B D2 R D R2 B2 L B'",
    "L' B2 R D' B' D2 L' D' L2 B2 R' B",
  ],
  56: [
    "L F R F' L2 F U R' U' F' L",
    "R' F' L' F R2 F' U' L U F R'",
    "R B' R' B U2 R' U R U' B U2 B'",
    "L' B L B' U2 L U' L' U B' U2 B",
    "F R U R' U' R F' L F R' F' L'",
    "F' L' U' L U L' F R' F' L F R",
    "R U2 L' U R' U' L F2 L F L' F",
    "R' U2 L U' R U L' B2 L' B' L B'",
    "L F L' U R U' L R2 F R F2 L'",
    "L' B' L U' R' U L' R2 B' R' B2 L",
    "F' U' L U2 L U' L U L' U2 L' U' F",
    "F U R' U2 R' U R' U' R U2 R U F'",
    "B U L U' F U' F' L' U' L U L' B'",
    "B' U' R' U F' U F R U R' U' R B",
    "F R U R' U2 R' U2 R U F' R' U R",
    "F' L' U' L U2 L U2 L' U' F L U' L'",
    "R B' R' B U2 B U' B L' B' L U' B'",
    "L' B L B' U2 B' U B' R B R' U B",
    "F R U R' U2 B U B' F' U2 B U B'",
    "B' R' U' R U2 F' U' B F U2 F' U' F",
    "B U' R' U L2 U' R U L' U L' U' B'",
  ],
  57: [
    "L U' L' U L R' F' L F L2 R",
    "L' R' U L U' L' R B L' B' L2",
    "L U L' B' F U R' U' R B F'",
    "R U B' U' B R' U B L' B' L",
    "R' U' F U F' R U' F' L F L'",
    "F2 L F L' F R U R' F' U' F",
    "F2 R' F' R F' L' U' L F U F'",
    "R B L U' L' B' U2 B U B' R'",
    "L' U' L' B' U' B U L2 U2 L' U' L",
    "F R U2 R' U F' L F' L' F2 U F'",
    "F' L' U2 L U' F R' F R F2 U' F",
    "R U2 R' U' R B U2 B' R' F' U F",
    "B U' B' L' R B2 R' U' B U B2 L",
    "R B U' B' U2 L R2 D' F D L' R",
    "L' U B2 F D' R' D B' F' L' B' L2",
    "F U L F' D R' F' R' D R2 D2 L'",
    "F L' D2 U2 R U' R' D2 U2 L U F'",
    "F R U2 R2 F2 D' F' D F' R U2 F'",
    "L U2 F' L D' L D L2 F2 U2 F' L'",
    "F' R U F R' D2 L2 D L' F' L' D",
    "D' B R' U' B' R D2 L2 D' L B L",
    "F2 U F2 R B L' U2 L B' R' U' F2",
    "B' R B2 F2 L' D L B2 F2 R' U' B",
    "L2 D' B2 D L2 B F R U2 R' B' F'",
    "B2 D' R2 F' L' B U2 B' L F D B2",
  ]
};
